# Analysis goals

1. Determine what data is relevant to show by a "results" object and its corresponding stats/plots.
2. Identify bugs or conceptual errors.
3. Examine runtime bottlenecks and determine how to speed up sim.

In [1]:
import pandas as pd
import pickle
import matplotlib.pyplot as plt
import pstats
import numpy as np

pd.set_option("display.max_columns", None)

In [2]:
with open("../pickles/scenario.pkl", "rb") as f:
    scenario = pickle.load(f)
with open("../pickles/metrics_processor.pkl", "rb") as f:
    metrics_processor = pickle.load(f)

In [8]:
market = list(scenario.markets.values())[0]
print(market)
reg = market.models[0][1]
size = int(1e6)
x = np.array([size]).reshape(-1, 1)

External Market (USDC, USDT)


In [81]:
def func(x):
    T = np.clip(x, reg.X_min_, reg.X_max_)
    return reg.f_(T)

In [57]:
%timeit reg.predict(x)

96.6 µs ± 1.84 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [61]:
%timeit func(x)

17.4 µs ± 2.55 µs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [72]:
func(x) == reg.predict(x)

array([[ True]])

In [82]:
func(x).dtype

float64


dtype('float64')

In [79]:
reg.predict(x).dtype

dtype('float64')

In [80]:
x.dtype

dtype('int64')

In [76]:
from sklearn.utils import check_array

T = check_array(x, dtype=np.float64, ensure_2d=False)
T.dtype

dtype('float64')

In [44]:
reg._check_input_data_shape(T)

In [46]:
T = np.clip(T, reg.X_min_, reg.X_max_)
T

array([[5.04572974e+08]])

In [40]:
reg.predict(x)

array([0.0002195])

In [41]:
reg.f_(x)

array([[nan]])

In [12]:
df = metrics_processor.df
df

timestamp  arbitrageur_profit  arbitrageur_count  keeper_profit  \
0   2023-12-06 22:47:19        16031.435765                  4            0.0   
1   2023-12-06 23:47:19        16327.928812                  7            0.0   
2   2023-12-07 00:47:19        17120.862197                  9            0.0   
3   2023-12-07 01:47:19        17972.936330                 13            0.0   
4   2023-12-07 02:47:19        18026.589062                 16            0.0   
..                  ...                 ...                ...            ...   
163 2023-12-13 17:47:19        42809.016433                300            0.0   
164 2023-12-13 18:47:19        43139.133781                302            0.0   
165 2023-12-13 19:47:19        43139.133781                302            0.0   
166 2023-12-13 20:47:19        43398.063562                304            0.0   
167 2023-12-13 21:47:19        43528.065656                307            0.0   

     keeper_count  liquidator_profit  liquidator_count  \
0               0       65012.788847                 1   
1               0       65013.931350                 2   
2               0       65013.931350                 2   
3               0       65013.931350                 2   
4               0       65013.931350                 2   
..            ...                ...               ...   
163             0       65034.709519                 3   
164             0       65034.709519                 3   
165             0       65034.709519                 3   
166             0       65034.709519                 3   
167             0       65034.709519                 3   

          llamma_WETH_price llamma_WETH_oracle_price  llamma_WETH_fees_x  \
0    2245711730308338024482   2252689216320075464704             2636248   
1    2244934322013356681333   2248746093350448456143             3979890   
2    2244912297744144078326   2248762332647248126239             4952489   
3    2236181810574026409535   2240157459709222562666             6645836   
4    2233106649400888984982   2237344414959467643201             9023913   
..                      ...                      ...                 ...   
163  2311442385892754414359   2302635224419952570894           185379749   
164  2311592508620186528139   2302709638948980889783           186550488   
165  2334914722864171193806   2310489301085529349024           187142297   
166  2344564590055648522000   2317968950946133236651           188919328   
167  2350144427669697179073   2320515317163759002657           190265444   

     llamma_WETH_fees_y          llamma_WETH_bal_x        llamma_WETH_bal_y  \
0                     0   794465331942950411210999  12646117928609448025432   
1                     0   883525463828914581431284  12606572595980065876253   
2                     0   883525463828914581431284  12606572595980065876253   
3                     0  1020838271090489141296674  12545303998771444257372   
4                     0  1064772417789156317629098  12525724423233631040313   
..                  ...                        ...                      ...   
163                   0   204602357139549326245016  12883407557995496941498   
164                   0   204602357139549326245016  12883407557995496941498   
165                   0   204602357139549326245016  12883407557995496941498   
166                   0   112857877927602842040491  12922666295796955878842   
167                   0    98289298516369247192533  12928900011066472852922   

     controller_WETH_system_health   controller_WETH_bad_debt  \
0                     4.061528e+17  6582755539915736668938240   
1                     4.037375e+17  6582755539915736668938240   
2                     4.037188e+17  6582755539915736668938240   
3                     3.984447e+17  6582755539915736668938240   
4                     3.967183e+17  6582755539915736668938240   
..                             ...                        ...   
163                   4.318

In [13]:
# # LLAMMA price
# (df["llamma_WETH_price"].astype(float) / 1e18).plot("Spot Price")
# (df["llamma_WETH_oracle_price"].astype(float) / 1e18).plot(label="Oracle Price")
# # TODO does it make sense that oracle price is a muted version of LLAMMA price?

## Runtime Profile

In [16]:
prof = pstats.Stats("../logs/sim.prof")
prof.sort_stats(pstats.SortKey.CUMULATIVE)
prof.print_stats()

Wed Dec  6 22:54:23 2023    ../logs/sim.prof

         294239805 function calls (287066865 primitive calls) in 424.300 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.002    0.002  424.360  424.360 /root/crvUSDrisk/src/sim/__init__.py:16(sim)
      168    0.003    0.000  400.850    2.386 /root/crvUSDrisk/src/sim/scenario.py:166(perform_actions)
      168    0.004    0.000  374.932    2.232 /root/crvUSDrisk/src/agents/arbitrageur.py:35(arbitrage)
      475    0.021    0.000  374.490    0.788 /root/crvUSDrisk/src/agents/arbitrageur.py:92(find_best_arbitrage)
     9500    0.038    0.000  374.469    0.039 /root/crvUSDrisk/src/trades/cycle.py:77(optimize)
     7658    0.073    0.000  373.410    0.049 /root/crvUSDrisk/src/trades/cycle.py:182(_optimize_mem)
     7658    0.132    0.000  368.872    0.048 /root/crvUSDrisk/venv/lib/python3.11/site-packages/scipy/optimize/_minimize.py:754(minimize_scalar)
     7658   1